default:
    just --list

build:
    pnpm next build

run:
    pnpm next dev

start:
    pnpm next start

lint:
    pnpm eslint

add *ARGS:
    pnpm add {{ARGS}}

install:
    pnpm i

test:
    echo "Running tests..."

db-generate:
    pnpm exec drizzle-kit generate

db-migrate:
    pnpm exec drizzle-kit migrate

db-migrate-down:
    pnpm exec tsx scripts/db-down.ts

db-studio:
    pnpm exec drizzle-kit studio
