dir := "apps/web"
set working-directory := "../../"

build:
    cd {{dir}} && pnpm build

run:
    cd {{dir}} && pnpm dev

clean:
    cd {{dir}} && pnpm clean

add *ARGS:
    cd {{dir}} && pnpm add {{ARGS}}

install:
    cd {{dir}} && pnpm i
