default:
    just --list

build:
    pnpm next build

run:
    pnpm next dev

start:
    pnpm next start

lint:
    pnpm eslint

add *ARGS:
    pnpm add {{ARGS}}

install:
    pnpm i

test:   
    echo "Running tests..."
