dir := "apps/ai-worker"
set working-directory := "../../"

build:
    cd {{dir}} && pnpm build

run:
    cd {{dir}} && uv run celery -A src.celery_app:app worker -Q ingestion --loglevel=info

add *ARGS:
    cd {{dir}} && uv add {{ARGS}}

install:
    cd {{dir}} && uv sync
